/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDrawerContentc: typeof import('naive-ui')['NDrawerContentc']
    NDrawerContentclo: typeof import('naive-ui')['NDrawerContentclo']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGr: typeof import('naive-ui')['NGr']
    NGre: typeof import('naive-ui')['NGre']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH: typeof import('naive-ui')['NH']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    'NInfinite-': typeof import('naive-ui')['NInfinite-']
    NInfiniteScroll: typeof import('naive-ui')['NInfiniteScroll']
    NInp: typeof import('naive-ui')['NInp']
    NInpu: typeof import('naive-ui')['NInpu']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLi: typeof import('naive-ui')['NLi']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NRate: typeof import('naive-ui')['NRate']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NT: typeof import('naive-ui')['NT']
    NTa: typeof import('naive-ui')['NTa']
    NTag: typeof import('naive-ui')['NTag']
    NTe: typeof import('naive-ui')['NTe']
    NTex: typeof import('naive-ui')['NTex']
    NText: typeof import('naive-ui')['NText']
    NTextd: typeof import('naive-ui')['NTextd']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    NUl: typeof import('naive-ui')['NUl']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Proposal: typeof import('./src/components/Proposal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
